{"name": "test_delete2_cache", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Test_ziyun.test_DNC.Test_device_ml object at 0x000001DA206CE438>\n\n    @allure.story(\"文件再次删除到回收站\")\n    def test_delete2_cache(self):\n        rp_resp = requests.put(url + '/file/delete',\n                               json={'reason': '二次接口删除', 'fileId': fileId}, headers={'token': token_data})\n        assertions.assert_code(rp_resp.status_code, 200)\n        rp_resp_json = rp_resp.json()\n>       assertions.assert_in_text(rp_resp_json['message'], 'Success')\n\ntest_DNC.py:227: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Common.Assert.Assertions object at 0x000001DA1F5DA0F0>\nbody = 'Internal server error', expected_msg = 'Success'\n\n    def assert_in_text(self, body, expected_msg):\n        \"\"\"\n        验证response body中是否包含预期字符串\n        :param body:\n        :param expected_msg:\n        :return:\n        \"\"\"\n        try:\n            text = json.dumps(body, ensure_ascii=False)\n            # print(text)\n>           assert expected_msg in text\nE           AssertionError\n\n..\\Common\\Assert.py:59: AssertionError"}, "attachments": [{"name": "log", "source": "1dec98ed-92c4-488c-a8d5-79f0d6803dd6-attachment.txt", "type": "text/plain"}], "start": 1600413559743, "stop": 1600413560251, "uuid": "e3fcefe9-8b60-4397-b805-996f60a9b2d1", "historyId": "4695cf4640d6b62fead14547b029aba4", "testCaseId": "4e4726aee5591780e9c760575bb903fd", "fullName": "test_DNC.Test_device_ml#test_delete2_cache", "labels": [{"name": "feature", "value": "设备目录分发页、回传页接口"}, {"name": "story", "value": "文件再次删除到回收站"}, {"name": "suite", "value": "test_DNC"}, {"name": "subSuite", "value": "Test_device_ml"}, {"name": "host", "value": "DESKTOP-FIOLAUQ"}, {"name": "thread", "value": "41740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_DNC"}]}